### ISSUE TITLE
Como se instala ? 

### ISSUE THREAD

**Issue by tdcomcl** [roycer/LibreDTE_backend#1]
Hola, me guastaría probar el backend, es posible que expliques como se instala? 

Saludos

**Comment by roycer** [comment]
- `composer install ` (dependencias)
- `docker build -t php720:1.4 .` (crear imagen)
- `docker-compose up -d` (levanta los contenedores)
- `cp .env.example .env` (variables)
- `php artisan migrate` (dentro del contenedor para generar la BD)

tmb es necesario tener tu certificado digital para emitir documentos, esto lo copias en `resources`

Saludos

**Comment by roycer** [comment]
> Hola, me guastaría probar el backend, es posible que expliques como se instala?
> 
> Saludos

- `composer install` (dependencias)
- `docker build -t php720:1.4 .` (crear imagen)
- `docker-compose up -d` (levanta los contenedores)
- `cp .env.example .env` (variables)
- `php artisan migrate` (dentro del contenedor para generar la BD)

tmb es necesario tener tu certificado digital para emitir documentos, esto lo copias en resources

Saludos
